environment:
  package_semantic_version: 4.0.0
  assembly_semantic_version: 4.0.0

version: $(package_semantic_version).{build}

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(assembly_semantic_version).0'
  assembly_file_version: '$(appveyor_build_version)'
  assembly_informational_version: '$(package_semantic_version)-CI-{build}'

configuration: Release

before_build:
- nuget restore

build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true

deploy:
- provider: NuGet
  server: https://www.myget.org/F/autofac/
  api_key:
    secure: N4KZCRegcmenMoJ0peZfQwDzqq+Wt4oxGzNTgvkrDxgWyZhw7hNwKmd4n2AsNKQX
  symbol_server: https://nuget.symbolsource.org/MyGet/autofac
